### PR TITLE
Add responsive scroll bar

### PR DESCRIPTION
**Pull request by RIanDeLaCruz**
Add responsive scrollbar for small width screens and large tables

### CODE REVIEW

**Comment by RIanDeLaCruz** [comment]
For Issue #37

**Comment by xaksis** [comment]
Hey thanks @RIanDeLaCruz ! Just tested and looks good. Could you resolve the conflict and rebase with latest? I'll merge it.

**Comment by RIanDeLaCruz** [comment]
@xaksis Would you be the one to do a build? Conflicts in the dist are due to my folders showing up during build time

**Comment by RIanDeLaCruz** [comment]
@xaksis I added a build that has my PR and the updated master of the project

**Pull request merged**
