### PR TITLE
Bug Fix: Row Actions were resetting Column Sorting back to Initial Sort

### PR DESCRIPTION
**Pull request by HaydenHodge**
In Reference to this Issue: https://github.com/xaksis/vue-good-table/issues/626

Location of Change: Table.vue#495

I uncommented out the 'if' statement wrapping the 'intializeSort()' function. Without it, any row actions would lead to the 'initializeSort()' function resetting the column sorting back to the 'initialSortBy' value.

Old:
```
    sortOptions: {
      handler(newValue, oldValue) {
        // if (!isEqual(newValue, oldValue)) {
        this.initializeSort();
        // }
      },
      deep: true,
    },
```
New:
```
    sortOptions: {
      handler(newValue, oldValue) {
        if (!isEqual(newValue, oldValue)) {
          this.initializeSort();
        }
      },
      deep: true,
    },
```

### CODE REVIEW

**Comment by TheJaredWilcurt** [comment]
I endorse this.

Fixes #626 

@xaksis is there a reason to run the `initializeSort` when the `newValue` and `oldValue` are identical?

**Comment by TheJaredWilcurt** [comment]
@xaksis In case you don't want the dist changes too, I have made a separate PR.

* https://github.com/xaksis/vue-good-table/pull/636

This bug is preventing us from moving forword on tickets at work that rely on custom sorting functions.

**Comment by xaksis** [comment]
@HaydenHodge @TheJaredWilcurt this was introduced when solving for #577. I'm accepting @TheJaredWilcurt's PR which will probably bring back the bug in #577. But this is a bigger issue so will revert while I investigate a proper fix for #577.

**Comment by chasegiunta** [comment]
@xaksis btw, I think there was a much bigger problem that you fixed as well. That is, when using remote mode, and setting an initial sort by, the remote call (for some reason unknown to me) would continually & repeatedly make the initial sort by request. Updating to 2.8.1 from 2.8.0 fixed this for me.

**Pull request closed without merging**
