### PR TITLE
Customizable "Rows per page" dropdown

### PR DESCRIPTION
**Pull request by maurocasas**
Right now, when you add a custom Per Page value, it's added to the dropdown but it also adds the other options, which is making it look weird.

This pull request will allow to customize the dropdown, add whatever options you need, and won't break the current codebases out there.

It's also got a watcher in order to change the setting on the fly.

Use cases:

1. You set a *perPage* value. We take the default options and add your custom *perPage* to the dropdown
2. You set a custom dropdown, perPage is disregarded in the dropdown.
3. You set nothing, you get the defaults

### CODE REVIEW

**Comment by maurocasas** [comment]
@xaksis Hey man! check this one out when you can please, we want this feature on our platform, but I also think it comes handy to the component you've built 👏

**Comment by xaksis** [comment]
@maurocasas great! Sorry I've been a bit busy lately, I'll review this today/tomorrow. Thank you for your patience.

**Comment by xaksis** [comment]
@maurocasas there are two pagers on Table.vue, you seem to have only updated the bottom pager. could you please add the property on the top instance as well?

**Comment by xaksis** [comment]
@maurocasas also, in the watcher, you'd need to take care of setting it to default, in case the customPerPageDropdown is set to `null` or `[]`. Again, thank you for your contributions!

**Comment by maurocasas** [comment]
@xaksis there you go buddy! :D

**Comment by xaksis** [comment]
@maurocasas hey thanks! could you please rebase from master once more... I was going to do it via github but the dist files have way too many conflicts to do this manually. Thanks!

**Comment by maurocasas** [comment]
@xaksis Thanks for taking care of it, appreciated, couldn't find the time to wrap up.

**Comment by xaksis** [comment]
@maurocasas no problem. However i'm still seeing some issues like default options not rendering for paging dropdown, and paging acting a bit weird with search. will look into these before i cut a new release.

**Pull request merged**
