### PR TITLE
remove some lodash functions

### PR DESCRIPTION
**Pull request by g-plane**
Ref: #350

### CODE REVIEW

**Comment by xaksis** [comment]
This results in all sorts of duplicate key errors. Reverted for @g-plane to investigate.

**Comment by g-plane** [comment]
What does it mean?

**Comment by g-plane** [comment]
I have removed two lodash functions (`foreach` and `filter`). Which removal did cause the problem?

**Comment by xaksis** [comment]
I don't believe filter was being used anywhere... so it must be foreach. Try running the dev app in the repo, you'll see the errors I'm talking about.

**Comment by g-plane** [comment]
So maybe we can remove `lodash.filter` again?

**Comment by xaksis** [comment]
good point, will get rid of filter in next release.

**Pull request merged**
