### PR TITLE
feat: emit an event when filtered rows change

### PR DESCRIPTION
**Pull request by fleetofthemalden**
# Description

Our org needs to be able to display an updated results count when filtering happens. This solves that problem by emitting an event when the filteredRows are set

Fixes # (none)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [x] Used `dev/App.vue` to console log event params

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by fleetofthemalden** [comment]
@xaksis How best can I update any documentation for this feature? The html blob looks almost like it was generated. Should I be adding some tests?

**Comment by xaksis** [comment]
hey @fleetofthemalden could you help me understand why we need this event? Ideally, we should only emit events for user invoked interactions. We might be changing the rows for internal reasons (think internal rowIds, etc) where an external event might be undesirable. 
Are their any table events missing that this is taking care of?

**Comment by fleetofthemalden** [comment]
Thanks for the prompt response!
> hey @fleetofthemalden, could you help me understand why we need this event? Ideally, we should only emit events for user invoked interactions. We might be changing the rows for internal reasons (think internal rowIds, etc) where an external event might be undesirable.
> Are there any table events missing that this is taking care of?

That's a fair point. My initial idea was just to add a `filteredResultsCount` or `filteredRowsCount` param to the `onColumnFilter` event. Because all I need is to be able to do is update our results count in a different component when filtering occurs. I ended up going this route because I thought there may be wider appeal to other devs beyond my narrow use-case. I was thinking of it as analogous to an `onChange` event. 

If adding the count (or the rows themselves) to the `onColumnFilter` is a better route, I'm perfectly happy to do that. But that will involve moving a few code blocks around. 

Let me know what's the best way to proceed

**Comment by xaksis** [comment]
@fleetofthemalden you can get the filteredRows at any time by putting a ref on the table: 
```
<vue-good-table
  ref="myTable"
  @on-column-filter="onColumnFIlterHandler"
  ...
</vue-good-table>

// later in your handler
methods: {
  onColumnFilterHandler(params) {
    const filteredRows = this.$refs.myTable.filteredRows.map(row => row.children);
    const filteredRowCount = filteredRows.length;
  }
}
```

**Comment by fleetofthemalden** [comment]
yeah that works too. I'm slightly anti-ref just because it invites state mutation, but if this feature isn't wanted, I can close this out. Thanks again!

**Comment by fleetofthemalden** [comment]
Hey @xaksis So it turns out this solution runs into the same problem I initially noticed when I was adding the parameter to `onColumnFilter` event: The event is fired before the filtering actually happens. If I can find some time, I'm going to open another PR to move the event logic after the filtering logic. Stay tuned.

**Pull request closed without merging**
