### PR TITLE
Adds middle mouse click event to row

### PR DESCRIPTION
**Pull request by dalecarslaw**
Emits an event when user clicks on row with middle mouse button using vue auxclick event.

### CODE REVIEW

**Comment by dalecarslaw** [comment]
Please review

**Comment by ow-en** [comment]
@dalecarslaw will review this tonight and get back to you. Thanks for the contribution.

**Comment by ow-en** [comment]
@dalecarslaw This will be merged tomorrow with a couple of other fixes. Thanks for your contribution.

**Comment by dalecarslaw** [comment]
@ow-en Is this still waiting to be merged?

**Pull request merged**
