### PR TITLE
Extract paginatin to an extern component

### PR DESCRIPTION
**Pull request by tonimc**
This PR create the `vue-good-pagination` component to maintains pagination decoupled form `vue-good-table` and give the ability to play with it.

In the PR the user have the option to change the position of the pagination with the boolean prop `paginationOnTop` added to `vue-good-table`.

### CODE REVIEW

**Comment by cristijora** [comment]
Very nice @tonimc Although I am not a collaborator/maintainer here I would totally agree with such a change since it's a step further to make the component more modular.
An addition on top of what you did would be to wrap the pagination parts in slots

```html
<slot name="table-header>
 //pagination here
</slot>

<slot name="table-footer>
 //pagination here
</slot>
```

This would allow using a custom pagination of own preference.

**Comment by xaksis** [comment]
@tonimc will review over the weekend. Thank you!

**Comment by tonimc** [comment]
Thanks, @xaksis.

@cristijora I understand your point but in terms of giving to a user a data table easy & quick to use I mean that it's a good point provide the pagination already integrated.

Maybe, a better approach could be if we extract the table to another component and allow to user use both components separated if he likes but maintain `vue-good-table` as a component who already integrate these 2 components (table and pagination) in case the user would like something easy & quick and don't wanna spend time on that.

**Comment by xaksis** [comment]
@tonimc This is really great! The next step for me is to break the component into smaller modules, was going to do it in my down time. Thank you for a great start.

**Pull request merged**
