### PR TITLE
Bundle size optimizations.

### PR DESCRIPTION
**Pull request by Herz3h**
Replace date-fns by dayjs to reduce bundle size.
Replace lodash's each, assign, filter by native functions.
Add rollup-plugin-visualizer.

Before:
Capture d’écran 2020-08-04 à 13 37 36

After:
Capture d’écran 2020-08-04 à 14 02 03

### CODE REVIEW

**Comment by p0psicles** [comment]
You can't just swap out date-fns with dayjs. They both have different templating.
https://day.js.org/docs/en/parse/string-format vs https://date-fns.org/docs/format

Can't expect users to adjust their formats?

**Comment by p0psicles** [comment]
Can't we use es6 tree-shaking in stead?
https://date-fns.org/v2.0.0-alpha.7/docs/ECMAScript-Modules#tree-shaking

**Comment by Herz3h** [comment]
I only checked the parse format, which in both cases seem to accept ISO 8601 format by default. Hence the replacement. Will give tree-shaking a try tomorrow.

**Comment by Herz3h** [comment]
I put back date-fns in and tried date-fns/esm module, but not difference at all in bundle size.

Here is current bundle size:

image

**Comment by p0psicles** [comment]
Yeah it's a build issue with poi/webpack https://github.com/egoist/poi/issues/327

**Comment by Herz3h** [comment]
I'm not familiar with poi/bili, but `npm run bundle` runs bili apparently, isn't that based on rollupJS ?

**Comment by p0psicles** [comment]
@xaksis ?

**Comment by xaksis** [comment]
hmm, curious. We do use bili for bundling which uses rollup internally. My memory is a bit fuzzy but this might be happening because of an issue with vue-rollup - https://github.com/egoist/bili/issues/221 where we had to use inline bundling for esm file.
original issue on vgt - https://github.com/xaksis/vue-good-table/issues/569
I didn't get a chance to go back into it but that would be a good start to investigate, to see if we can revert the inline module bundling. basically remove this line: https://github.com/xaksis/vue-good-table/blob/master/bili.config.js#L34
and have the esm file not throw the error mentioned above.

**Comment by xaksis** [comment]
On another note, I think we can also replace lodash.foreach, lodash.filter, & lodash.assign with their es6 counterparts now and reduce the bundle size further. 🙏

**Comment by Herz3h** [comment]
Fixed conflicts

**Comment by xaksis** [comment]
v2.21.6 contains these changes.

**Pull request closed without merging**
