### PR TITLE
Add optional sortable columns

### LINKED ISSUE #86: Column sorting
Is it possible to add a feature to be able to disable specific column sorting instead of all columns?

### PR DESCRIPTION
**Pull request by VitorLuizC**
Added a property "sortable" that is stronger than global sortable option and let any column be or not be sortable. This fixes #86 issue.

I'd used the code style defined on ESLint settings and added JSDoc on methods changed on this change. I really don't know if this is the right approach since component's code haven't used the code style.

### CODE REVIEW

**Comment by xaksis** [comment]
@VitorLuizC thank you for your PR. I'll review this shortly and update here.

**Comment by xaksis** [comment]
@VitorLuizC I'm sorry it's taken this long. This PR does quite a bit more than what the title says. Any chance you can separate out the fix for #87 from this so I can merge that in. Then we can look into the stylistic changes after that. I know this request might be annoying, but i'll really appreciate it! Thank you in advance!

**Comment by VitorLuizC** [comment]
@xaksis I've replaced the JSDoc comments with your style comments and added semicolons to my methods.

**Comment by VitorLuizC** [comment]
@xaksis should I make another PR changing all style to follow ESLint settings you have defined on root or you'll just delete it?

**Comment by xaksis** [comment]
The following code is buggy as well: 
```
const classes = Object.assign({}, this.getClasses(index, 'th'), {
 +          'sorting': isSortable,
 +          'sorting-desc': isSortable && isDescending,
 +          'sorting-asc': isSortable && !isDescending
 +        });
```
there are 3 states for each column... descending, ascending, no sort. the above doesn't take care of no sort. default is always ascending even though there's no sort applied to the columns.

I will fix this.

**Pull request merged**
