### PR TITLE
Feature: reset sorting after third click on column header

### PR DESCRIPTION
**Pull request by TilmannF**
Addresses #794

### CODE REVIEW

**Comment by xaksis** [comment]
Hey @TilmannF, have you been able to test this? the 3rd click doesn't really reset the sort but it leaves it in the initial sort.

**Comment by TilmannF** [comment]
Yes, I tested it with single & multiple sort. Could you provide an example?

**Comment by xaksis** [comment]
If you take a look at the example in the codebase (App.vue). You'll see what I'm talking about. 
The changes that you've added, just tells the table to not do anything if it's the 3rd sort ('none'). But this doesn't revert the default sort into unsorted rows. That original sorting is lost the minute someone hits sort.

**Comment by xaksis** [comment]
This is now implemented. https://github.com/xaksis/vue-good-table/commit/20068fcecc6e42ed6cb2c6d62c3ba3646bf04828

**Pull request closed without merging**
