### PR TITLE
Fix bug with sorting applied to other colums having using function fields

### PR DESCRIPTION
**Pull request by p0psicles**
* Changed dev/App.vue to highlight the issue.

codesandbox that shows the issue: https://codesandbox.io/s/clever-fog-2lfgg

@xaksis I'm not 100% sure this is the proper way of fixing this. I'm also not a full fledged js engineer. But the way it's now, using bound functions as fields, can cause multiple issues throughout the app.

I"m using function.name, to translate the bound function to something like: `bound functionName`.

This at least fixes my issue. Where when i'm using multiple bound functions for the fields, sorting one will also sort the other.

You might want to look into something a little less hacky? But that would require to refactor parts of the app. And store the field functions in a different format?

### CODE REVIEW

**Comment by xaksis** [comment]
Hy @p0psicles the codesandbox shows me a default vue app. Am I missing something or was the sample code not saved?

**Comment by p0psicles** [comment]
Try this? I don't use codesandbox that often..
https://codesandbox.io/s/exciting-lehmann-msen0

**Comment by p0psicles** [comment]
Any update on this?

**Comment by xaksis** [comment]
The only issue here is that the function name can be `''` or `anonymous` which isn't unique. So i'll need to modify the getField function a bit before rollout.

**Pull request merged**
