### PR TITLE
Add the default sort type

### PR DESCRIPTION
**Pull request by okoriko**
Currently when a column is sorted, it defaults to sort it by ascending order.
This PR provides the possibility to configure the default order.

To sort columns by descending order first, add the following as a table option:
```
:sort-options="{defaultSortType: 'desc'}"
```

### CODE REVIEW

**Comment by roberto910907** [comment]
@okoriko You could also add the documentation update to reflect this new option. WDYT?

**Comment by xaksis** [comment]
@okoriko I'm in the process of re-writing some of the sort logic. Will need to hold off on this merge.

**Comment by virinchi22** [comment]
Anyone knows how to sort by time??

**Comment by xaksis** [comment]
sort has changed significantly since this PR. I'm going to close this.

**Pull request closed without merging**
