### PR TITLE
Check box table proposal

### PR DESCRIPTION
**Pull request by tonimc**
First of all, thanks @xaksis for the improvements made on the latest versions of the project. Good work :clap: 

This PR is a proposal to change the behavior of how Checkbox Table works right now.
This PR propose:
- Select all rows when the user clicks on the global checkbox instead select only the rows of the current page.
- Improve some little possible incoherence with the use of `v-model` directive.
- Add `on-selected-rows-change` events to follow the prop/events communication pattern between components.

### CODE REVIEW

**Comment by tonimc** [comment]
Hey, @xaksis Did you have time to take a look at this PR?

**Comment by xaksis** [comment]
hey @tonimc! I apologize that it has taken me so long to review this... lots of stuff going on career wise so I was a bit busy. I aim to review it this week. There are a few things about the proposed behavior that I want to discuss with you... let me look into this in the next couple of days and put my thoughts up here.

**Comment by xaksis** [comment]
hey @tonimc so a few concerns with this PR:
 
1. Regarding `select all` functionality: A good majority checkbox table examples that you'll see, only allows you to select the visible rows so as to minimize confusion. check out gmail for example, or [this example](https://www.gyrocode.com/articles/jquery-datatables-checkboxes/). 
Having said that, I also see the utility of your use-case (select everything in the table) is it possible to keep both behaviors and have the users select which behavior they want. `selection-option.mode` perhaps.

1. With your PR, the selected rows are not reset on search, however the info div on top "3 rows selected" disappears if the filtered result has none of the selected rows. And if the filter doesn't match any rows then the select-all checkbox gets automatically selected.

1. column filters are throwing an error. I didn't debug it too much but looks like filter-changed is emitted with undefined params. 

1. This is just out of my curiousity - Why using :checked is better than v-model? 

Let me know when you've had a chance to look into these.

**Comment by tonimc** [comment]
Hi @xaksis, I couldn't reply previously but I will try to send new commits in the next days to accomplish what you said.
About waht you mention:
1) It's a good idea give to the user the ability to chose between the two behaviors, I will send new code to do allow that.
2) I thought that I check that but I will take a look again and fix the bug.
3) Same as in 2.
4) I used checked because I use a `computed` variable instead of a data, so the checkbox is checked if all rows are selected and it's not necessary to maintain another `data` for that.

Thanks guay I will jump on all of this ASAP

**Comment by tonimc** [comment]
@xaksis I dev the changes requested and bug fixes.
Right now the selection has a default mode as you suggested, and it has an option `selection-option.selectAllByPage` to `true` and if the user wants to select-all checks the entire dataset, only has to set to `false`.
I had added an indeterminate state on the checkbox to indicate that some rows are selected, as you can see.
kapture 2018-06-06 at 9 33 00

**Comment by xaksis** [comment]
@tonimc, you got it! will do this today.

**Comment by xaksis** [comment]
@tonimc thanks again!

**Pull request merged**
