### PR TITLE
Fixes issue with All in per page dropdown not staying selected

### PR DESCRIPTION
**Pull request by jjmartucci**
Addresses issue 676 https://github.com/xaksis/vue-good-table/issues/676

### CODE REVIEW

**Comment by jjmartucci** [comment]
Hi @xaksis it looks like this is still an issue in the latest release, what would it take to get it out for the next one?

**Comment by xaksis** [comment]
ooh, thanks for pinging. I'll make sure it goes out in this weekend's release. Will review and let you know if there are any changes needed by Wed. Thank you for your patience, @jjmartucci!

**Comment by xaksis** [comment]
hey @jjmartucci could you please remove the built files from your PR. Just the source changes are fine.

**Comment by jjmartucci** [comment]
Fixed

**Comment by p0psicles** [comment]
@jjmartucci can you help me explain what the exact issue is, that is fixed? Because I asumed that if you selected "All", it should return in the `@on-per-page-change` event, also that the keyword 'All'. But it's returning the total number of rows for me?

**Comment by jjmartucci** [comment]
> @jjmartucci can you help me explain what the exact issue is, that is fixed? Because I asumed that if you selected "All", it should return in the `@on-per-page-change` event, also that the keyword 'All'. But it's returning the total number of rows for me?

The initial issue was that if you selected "ALL" in the per-page dropdown, then changed the search criteria, the "ALL" text would disappear from the dropdown.

**Comment by p0psicles** [comment]
Ok, tnx. Is clear now. 

Hmm, i "solved" my issue by comparing the total rows that you get back when selecting all, to the total rows count. And then storing the perPage value as -1

**Pull request merged**
