### PR TITLE
Add 'visible' column property. Useful when you don't want to show col…

### PR DESCRIPTION
**Pull request by dolfinitylearning**
…umns to users, but still want it available to onClick.

### CODE REVIEW

**Comment by xaksis** [comment]
@dolfinitylearning I removed the demo directory from the project in favor of a live demo site: https://xaksis.github.io/vue-good-demos/#/simple-table. Just wanted to let you know... think it's easier to view it that way.

**Comment by xaksis** [comment]
@dolfinitylearning do you mind changing the 'visible' property to optional 'hidden' property? since columns would more often be visible than hidden, it makes sense to just add hidden=true for the lesser frequent event. What do you think?

**Comment by dolfinitylearning** [comment]
Re visible: I'm not sure it's needed after all. Just don't add a <td> for the column in the template. What do you think?

**Comment by xaksis** [comment]
yeah good point. only have columns for properties you want to show. going to reject this pull request then if that's ok

**Comment by dolfinitylearning** [comment]
Reject is fine. I didn't think it through. Been creating a prototype interface with your component, and it's working well.

**Pull request closed without merging**
