### PR TITLE
Add search query prop to Table component

### PR DESCRIPTION
**Pull request by vinnybod**

### CODE REVIEW

**Comment by xaksis** [comment]
@vinnybod sorry for the delay on this, week has been pretty hectic. I plan on looking it over tomorrow morning.

**Comment by vinnybod** [comment]
@xaksis I rebased on your new changes

**Comment by xaksis** [comment]
@vinnybod thanks again! there will be a few more changes coming in. I'm just adding the fixes that don't require a major version upgrade before we decide to merge this pull request.

**Comment by vinnybod** [comment]
Alright I will wait on that then :+1:

**Pull request closed without merging**
