### PR TITLE
optional HTML label (for font icons)

### PR DESCRIPTION
**Pull request by kreejzak**

### CODE REVIEW

**Comment by xaksis** [comment]
@kreejzak what is the purpose of the 'icon' class in this pull request?

**Comment by kreejzak** [comment]
You can add different styles just for icon. For example I added display block and text align center just for icons. Other, non html, labels are aligned to left.

**Comment by xaksis** [comment]
@kreejzak I appologize for the delay on this, but I'm thinking a better approach here would be to use slots to let people customize not only html but also events, let me think about this some more tonight and I'll update you.

**Comment by kreejzak** [comment]
Okay, thank you! Let me know about your ideas. Maybe I could give you a hand?

**Comment by xaksis** [comment]
@kreejzak v1.14.0 now allows for custom columns. Here's a demo page: https://xaksis.github.io/vue-good-demos/#/dynamic-table
Thank you for your suggestions!

**Pull request closed without merging**
